In [42]:
from src.preprocessing import load_data

df = load_data("../data/raw/kosis_sgg_sex_age_net_migration_raw.csv", encoding="cp949")
df.head()

,행정구역(시군구)별,성별,연령별,항목,단위,2015 년,2016 년,2017 년,2018 년,2019 년,2020 년,2021 년,2022 년,2023 년,2024 년,2025 년,Unnamed: 16
0,서울특별시,남자,계,순이동[명],명,-74154.0,-74941.0,-55418.0,-62557.0,-33562.0,-41379.0,-58722.0,-22207.0,-20920,-26467.0,-18077.0,NaN
1,서울특별시,남자,0 - 4세,순이동[명],명,-8122.0,-8615.0,-6960.0,-7929.0,-4995.0,-4627.0,-4745.0,-3570.0,-3393,-3352.0,-2577.0,NaN
2,서울특별시,남자,5 - 9세,순이동[명],명,-3520.0,-3862.0,-2765.0,-3787.0,-1626.0,-2263.0,-2890.0,-1462.0,-721,-522.0,335.0,NaN
3,서울특별시,남자,10 - 14세,순이동[명],명,-1369.0,-1721.0,-896.0,-1338.0,-346.0,-812.0,-1310.0,-204.0,-35,105.0,316.0,NaN
4,서울특별시,남자,15 - 19세,순이동[명],명,-1147.0,-1294.0,-171.0,-312.0,653.0,-101.0,-689.0,1762.0,1624,1945.0,2182.0,NaN

In [43]:
df_long = df.melt(
    id_vars=["행정구역(시군구)별", "성별", "연령별"],
    value_vars=[col for col in df.columns if "년" in col],
    var_name="year",
    value_name="net_migration"
)

In [44]:
df_long.head()

  행정구역(시군구)별  성별       연령별    year  net_migration
0      서울특별시  남자         계  2015 년       -74154.0
1      서울특별시  남자    0 - 4세  2015 년        -8122.0
2      서울특별시  남자    5 - 9세  2015 년        -3520.0
3      서울특별시  남자  10 - 14세  2015 년        -1369.0
4      서울특별시  남자  15 - 19세  2015 년        -1147.0

In [45]:
df_long['region'] = df['행정구역(시군구)별']
df_long['sex'] = df['성별']
df_long['age_group'] = df['연령별']

In [46]:
df_long.drop(columns=["행정구역(시군구)별", "성별", "연령별"], inplace=True)

In [48]:
df_long.head(20)

      year  net_migration region sex    age_group
0   2015 년       -74154.0  서울특별시  남자            계
1   2015 년        -8122.0  서울특별시  남자       0 - 4세
2   2015 년        -3520.0  서울특별시  남자       5 - 9세
3   2015 년        -1369.0  서울특별시  남자     10 - 14세
4   2015 년        -1147.0  서울특별시  남자     15 - 19세
5   2015 년         4270.0  서울특별시  남자     20 - 24세
6   2015 년         2277.0  서울특별시  남자     25 - 29세
7   2015 년       -12191.0  서울특별시  남자     30 - 34세
8   2015 년       -12528.0  서울특별시  남자     35 - 39세
9   2015 년        -8578.0  서울특별시  남자     40 - 44세
10  2015 년        -5861.0  서울특별시  남자     45 - 49세
11  2015 년        -5793.0  서울특별시  남자     50 - 54세
12  2015 년        -6445.0  서울특별시  남자     55 - 59세
13  2015 년        -5414.0  서울특별시  남자     60 - 64세
14  2015 년        -4408.0  서울특별시  남자     65 - 69세
15  2015 년        -3064.0  서울특별시  남자     70 - 74세
16  2015 년        -1517.0  서울특별시  남자     75 - 79세
17  2015 년         -744.0  서울특별시  남자        80세이상
18  2015 년        -5723.0  서울특별시  남자  청년층(19-34세)
19  2015 년       -63102.0  서울특별시  여자            계

In [49]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113278 entries, 0 to 113277
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   year           113278 non-null  object
 1   net_migration  112790 non-null  float64
 2   region         10298 non-null   object
 3   sex            10298 non-null   object
 4   age_group      10298 non-null   object
dtypes: float64(1), object(4)
memory usage: 4.3+ MB

In [50]:
df_long["year"] = df_long["year"].str.replace("년", "", regex=False).astype(int)

In [51]:
df_long.head(20)

    year  net_migration region sex    age_group
0   2015       -74154.0  서울특별시  남자            계
1   2015        -8122.0  서울특별시  남자       0 - 4세
2   2015        -3520.0  서울특별시  남자       5 - 9세
3   2015        -1369.0  서울특별시  남자     10 - 14세
4   2015        -1147.0  서울특별시  남자     15 - 19세
5   2015         4270.0  서울특별시  남자     20 - 24세
6   2015         2277.0  서울특별시  남자     25 - 29세
7   2015       -12191.0  서울특별시  남자     30 - 34세
8   2015       -12528.0  서울특별시  남자     35 - 39세
9   2015        -8578.0  서울특별시  남자     40 - 44세
10  2015        -5861.0  서울특별시  남자     45 - 49세
11  2015        -5793.0  서울특별시  남자     50 - 54세
12  2015        -6445.0  서울특별시  남자     55 - 59세
13  2015        -5414.0  서울특별시  남자     60 - 64세
14  2015        -4408.0  서울특별시  남자     65 - 69세
15  2015        -3064.0  서울특별시  남자     70 - 74세
16  2015        -1517.0  서울특별시  남자     75 - 79세
17  2015         -744.0  서울특별시  남자        80세이상
18  2015        -5723.0  서울특별시  남자  청년층(19-34세)
19  2015       -63102.0  서울특별시  여자            계

In [54]:
df_youth = df_long[df_long["age_group"] == "청년층(19-34세)"]

In [55]:
df_youth.head(10)

     year  net_migration region sex    age_group
18   2015        -5723.0  서울특별시  남자  청년층(19-34세)
37   2015         -505.0  서울특별시  여자  청년층(19-34세)
56   2015         -100.0    종로구  남자  청년층(19-34세)
75   2015         -110.0    종로구  여자  청년층(19-34세)
94   2015           76.0     중구  남자  청년층(19-34세)
113  2015           35.0     중구  여자  청년층(19-34세)
132  2015           91.0    용산구  남자  청년층(19-34세)
151  2015          254.0    용산구  여자  청년층(19-34세)
170  2015          767.0    성동구  남자  청년층(19-34세)
189  2015          752.0    성동구  여자  청년층(19-34세)